# Generated by Django 3.2.18 on 2023-04-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_uploads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploads',
        ),
        migrations.AddField(
            model_name='payment',
            name='back',
            field=models.ImageField(default='myimg.jpg', upload_to='upload/back'),
        ),
        migrations.AddField(
            model_name='payment',
            name='front',
            field=models.ImageField(default='myimg.jpg', upload_to='upload/front'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='event',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
