# Generated by Django 3.2.18 on 2023-04-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_tx_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='ayomide@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(max_length=25),
        ),
    ]
