# Generated by Django 3.2.18 on 2023-04-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20230412_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tel',
            field=models.CharField(default='0708', max_length=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
