# Generated by Django 3.2.18 on 2023-04-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20230412_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='tx_ref',
            new_name='txref',
        ),
        migrations.AlterField(
            model_name='payment',
            name='tel',
            field=models.CharField(max_length=12),
        ),
    ]
