# Generated by Django 3.2.18 on 2023-04-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20230413_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(default='2000.00NGN', max_length=20),
        ),
    ]
