# Generated by Django 3.2.16 on 2023-04-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='items',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
