# Generated by Django 3.2.18 on 2023-04-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20230413_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='not paid', max_length=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='back',
            field=models.ImageField(upload_to='upload/back'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='front',
            field=models.ImageField(upload_to='upload/front'),
        ),
    ]
