# Generated by Django 3.2.18 on 2023-05-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20230413_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='fail', max_length=4),
        ),
    ]
