# Generated by Django 3.2.18 on 2023-06-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='back',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='front',
        ),
    ]
