# Generated by Django 3.2.18 on 2023-02-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylsite', '0002_bootmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootmodel',
            name='picture',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bootmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bootmodel',
            name='valid',
            field=models.CharField(choices=[('Y', 'Valid'), ('N', 'Not Valid')], max_length=15),
        ),
    ]
