# Generated by Django 3.2.18 on 2023-02-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berylsite', '0003_auto_20230216_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bootmodel',
        ),
    ]
