# Generated by Django 3.2.18 on 2023-02-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylsite', '0006_clothmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootmodel',
            name='code',
            field=models.CharField(default='00001', max_length=10),
        ),
        migrations.AddField(
            model_name='clothmodel',
            name='code',
            field=models.CharField(default='00001', max_length=10),
        ),
    ]
