# Generated by Django 3.2.18 on 2023-04-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylsite', '0008_auto_20230325_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occassion', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('items', models.TextField()),
                ('itemsdetail', models.TextField()),
            ],
        ),
    ]
