# Generated by Django 3.2.18 on 2023-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berylsite', '0009_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
