# Generated by Django 3.2.18 on 2023-04-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylsite', '0010_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('items', models.TextField(blank=True)),
                ('itemsdetail', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
