# Generated by Django 3.2.18 on 2023-05-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylsite', '0012_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='greetingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=120)),
            ],
        ),
    ]
