# Generated by Django 3.2.18 on 2023-05-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylsite', '0013_greetingmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greetingmessage',
            name='message',
            field=models.TextField(max_length=120),
        ),
    ]
