# Generated by Django 3.2.18 on 2023-05-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylsite', '0015_auto_20230508_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('Y', 'Female')], max_length=7)),
                ('MobileNo', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bootmodel',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothmodel',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
