# Generated by Django 3.2.18 on 2023-05-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylsite', '0016_auto_20230508_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=7),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='MobileNo',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
